### ISSUE TITLE
评论框宽度问题

### ISSUE THREAD

**Issue by jingqinglin** [daidi/docsify-valine#3]
移动端设备旋转或电脑端最大化网页后，评论框宽度无法拉伸，如下：

![](https://gitee.com/JingqingLin/image-hosting/raw/master/img/1595135420469.gif)

应该是这句代码 `i.style="width: "+e.clientWidth+"px !important; margin: 0 auto 20px;"` 中的 `e.clientWidth` 导致的。一个可行的方案是改为 `i.style = "max-width: 80% !important; margin: 0 auto 20px;"`。

**Comment by daidi** [comment]
确实存在这个问题，我来修复一下，感谢！
